### PR TITLE
Tryout to Merge?

### PR DESCRIPTION
**Pull request by DavidKonijn**
Test

### CODE REVIEW

**Comment by spenceraxani** [comment]
Sorry, we're not accepting updates to the codebase or project.

**Comment by Phoenix1747** [comment]
What are you doing?

**Comment by PaulHearn92** [comment]
Not too sure about this question.  

 

However, I’ve just built 10 detectors, all worked first time, so very pleased.

 

Best wishes,

 

Paul.

 

Paul Hearn

Radio Astronomy Section Director

UKRAA Trustee

 

¦¦¦  British Astronomical Association  ¦¦ 

Burlington house, Piccadilly, W1J 0DU

 <https://britastro.org/section_front/24> https://britastro.org/section_front/24

 <https://www.youtube.com/user/britishastronomical/playlists> https://www.youtube.com/user/britishastronomical/playlists

   

e      ***@***.***> ***@***.***

a     RG6 1BU UK

t     +44 (0)7967 388 578

**Comment by Phoenix1747** [comment]
Why are you trying to merge your entire custom repo into Cosmic Watch v2? (https://github.com/spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2/pull/82)

**Pull request closed without merging**
